name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Publish
        run: npm publish --access public
